# Generated by Django 2.1.1 on 2018-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Accessed Model')),
                ('viewset', models.CharField(max_length=100, verbose_name='Accessed ViewSet')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Acess timestamp')),
                ('user', models.CharField(max_length=255, verbose_name='Accessing user')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('response', models.TextField(verbose_name='Response')),
            ],
            options={
                'verbose_name': 'data access log',
                'verbose_name_plural': 'data access logs',
            },
        ),
    ]
